### ISSUE TITLE
pip install miss the file DESCRIPTION.rst

### ISSUE THREAD

**Issue by Lancezh** [logandhead/ReactiPy#3]
Hi logandhead,

when I use command

```
$ pip install reactipy
```

It catches an error 

```
Downloading/unpacking reactipy
  Downloading ReactiPy-0.1.0.tar.gz
  Running setup.py egg_info for package reactipy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_lance/reactipy/setup.py", line 7, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/home/lance/local/python/lib/python2.7/codecs.py", line 881, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_lance/reactipy/DESCRIPTION.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_lance/reactipy/setup.py", line 7, in <module>

    with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:

  File "/home/lance/local/python/lib/python2.7/codecs.py", line 881, in open

    file = __builtin__.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_lance/reactipy/DESCRIPTION.rst'
```

You maybe miss the file **DESCRIPTION.rst** in **egg_info**, I think.

**Comment by logandhead** [comment]
Thanks for bringing this to my attention. I will fix tonight.

**Comment by Lancezh** [comment]
that's good for me, Thanks.  

I'm trying use Python render react  now ^_^

**Comment by logandhead** [comment]
Can you send me a pull request with the fix and I can push it up really quick?

**Comment by Lancezh** [comment]
I'm so sorry, I can't help, I never used **setuptools**.
